"""Agile velocity forecasting and risk-adjusted contingency.

Pure functions over frozen value objects: no I/O, no ORM, no wall clock. Every
entry point takes an explicit ``as_of`` date, which is what lets a report be
deleted and regenerated byte-identically from the same store.

``forecast_completion`` rolls the *last three* sprints of history (by
``ended_on``) into three velocities, hence three completion dates: **best** is
the window's max points (every remaining sprint as good as our best recent
one), **likely** its mean (recent form continues), **worst** its min. A wider
window smooths over the team changes that actually move velocity; a narrower
one is noise — so three, the usual agile convention, is the only window.

Chosen behaviour at the edges: **fewer than three sprints** uses what exists
(reported as ``sprints_used``) rather than refusing, since the first two
sprints of a project are when a band is most wanted; **empty history** is
refused with ``ValueError``, because a made-up number is worse than none;
**zero velocity** yields ``None``, the sentinel for "does not complete at this
velocity", and nothing else ever yields ``None``; **zero remaining points**
collapses all three dates to ``as_of`` even at zero velocity.

Monte Carlo simulation lives here too: ``monte_carlo_completion`` bootstrap-samples
past sprint velocities into a seeded ``MonteCarloForecast`` of p50/p80/p90
completion dates, independent of the best/likely/worst band above.
"""

from __future__ import annotations

import math
import random
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date, timedelta

VELOCITY_WINDOW = 3  # sprints of history rolled into the band
DEFAULT_CONTINGENCY_RATE = 0.10  # share of remaining budget held as contingency
DEFAULT_TRIALS = 1000  # Monte Carlo simulation runs
_MAX_SPRINTS = 1000  # guard against a run of zero-velocity samples never finishing


@dataclass(frozen=True)
class Sprint:
    """One *completed* sprint. In-flight sprints are not history."""

    name: str
    ended_on: date
    completed_points: float
    length_days: int = 14

    def __post_init__(self) -> None:
        if self.completed_points < 0 or self.length_days <= 0:
            raise ValueError(f"{self.name}: need completed_points >= 0 and length_days > 0")


@dataclass(frozen=True)
class Risk:
    """A risk-register line. ``impact`` is a cost in the project's currency."""

    name: str
    probability: float
    impact: float

    def __post_init__(self) -> None:
        if not 0.0 <= self.probability <= 1.0 or self.impact < 0:
            raise ValueError(f"{self.name}: need probability in 0..1 and impact >= 0")

    @property
    def exposure(self) -> float:
        """Probability-weighted cost of this risk."""
        return self.probability * self.impact


@dataclass(frozen=True)
class CompletionBand:
    """Best / likely / worst completion dates. ``None`` means "never at this velocity"."""

    as_of: date
    remaining_points: float
    sprints_used: int
    velocity_best: float
    velocity_likely: float
    velocity_worst: float
    best: date | None
    likely: date | None
    worst: date | None

    @property
    def completes(self) -> bool:
        """True when the *likely* case lands on a date at all."""
        return self.likely is not None


@dataclass(frozen=True)
class ContingencyAssessment:
    """Exposure across a risk register against the contingency held back."""

    as_of: date
    exposure: float
    contingency: float
    remaining_budget: float
    top_risk: str | None

    @property
    def covered(self) -> bool:
        """True when contingency is at least the total exposure."""
        return self.contingency >= self.exposure

    @property
    def shortfall(self) -> float:
        """Contingency still to be found; 0.0 when covered."""
        return max(0.0, self.exposure - self.contingency)

    @property
    def coverage_ratio(self) -> float | None:
        """Contingency as a multiple of exposure; ``None`` for an empty register."""
        if self.exposure == 0:
            return None
        return self.contingency / self.exposure


def _completion_date(
    remaining: float, velocity: float, sprint_days: float, as_of: date
) -> date | None:
    if velocity <= 0:
        return None
    sprints_needed = math.ceil(remaining / velocity)
    return as_of + timedelta(days=math.ceil(sprints_needed * sprint_days))


def forecast_completion(
    history: Sequence[Sprint], remaining_points: float, as_of: date
) -> CompletionBand:
    """Project ``remaining_points`` onto a completion band from sprint history.

    Raises ``ValueError`` on empty history or negative remaining points.
    """
    if not history:
        raise ValueError("sprint history is empty; nothing to forecast from")
    if remaining_points < 0:
        raise ValueError("remaining_points must be >= 0")

    # The tie-break on name keeps the window total-ordered: two sprints ending
    # the same day at the window boundary must not let input order pick the band.
    window = sorted(history, key=lambda s: (s.ended_on, s.name))[-VELOCITY_WINDOW:]
    points = [s.completed_points for s in window]
    sprint_days = sum(s.length_days for s in window) / len(window)
    best, likely, worst = max(points), sum(points) / len(points), min(points)

    dates: list[date | None]
    if remaining_points == 0:
        dates = [as_of, as_of, as_of]
    else:
        dates = [
            _completion_date(remaining_points, v, sprint_days, as_of) for v in (best, likely, worst)
        ]

    return CompletionBand(
        as_of=as_of,
        remaining_points=remaining_points,
        sprints_used=len(window),
        velocity_best=best,
        velocity_likely=likely,
        velocity_worst=worst,
        best=dates[0],
        likely=dates[1],
        worst=dates[2],
    )


def assess_contingency(
    register: Sequence[Risk],
    remaining_budget: float,
    as_of: date,
    contingency_rate: float = DEFAULT_CONTINGENCY_RATE,
) -> ContingencyAssessment:
    """Weigh a risk register's exposure against contingency held in the budget.

    Contingency is ``remaining_budget * contingency_rate``. Raises ``ValueError``
    on a negative budget or a rate outside 0..1.
    """
    if remaining_budget < 0:
        raise ValueError("remaining_budget must be >= 0")
    if not 0.0 <= contingency_rate <= 1.0:
        raise ValueError("contingency_rate must be between 0 and 1")

    exposure = sum(r.exposure for r in register)
    ranked = sorted(register, key=lambda r: (-r.exposure, r.name))
    return ContingencyAssessment(
        as_of=as_of,
        exposure=exposure,
        contingency=remaining_budget * contingency_rate,
        remaining_budget=remaining_budget,
        top_risk=ranked[0].name if ranked else None,
    )


@dataclass(frozen=True)
class MonteCarloForecast:
    """Completion percentiles from a seeded Monte Carlo over sprint velocities.

    A date is ``None`` when that percentile of trials never finished (a run of
    zero-velocity samples). ``p80`` is the usual planning commitment.
    """

    as_of: date
    remaining_points: float
    trials: int
    seed: int
    sprints_p50: int | None
    sprints_p80: int | None
    sprints_p90: int | None
    p50: date | None
    p80: date | None
    p90: date | None


def _percentile(sorted_outcomes: list[int | None], fraction: float) -> int | None:
    """The value at ``fraction`` through ``sorted_outcomes`` (``None`` sorts last)."""
    index = min(len(sorted_outcomes) - 1, math.ceil(fraction * len(sorted_outcomes)) - 1)
    index = max(0, index)
    return sorted_outcomes[index]


def monte_carlo_completion(
    history: Sequence[Sprint],
    remaining_points: float,
    as_of: date,
    seed: int,
    trials: int = DEFAULT_TRIALS,
) -> MonteCarloForecast:
    """Simulate completion by bootstrap-sampling past sprint velocities.

    Each trial draws sprint velocities (with replacement) from ``history`` until
    ``remaining_points`` is met, counting the sprints needed; the percentiles of
    that count become completion dates at the average sprint length. Fully
    seeded — the same ``seed`` gives byte-identical output — so nothing here
    reads the wall clock. Raises ``ValueError`` on empty history, negative points
    or a non-positive trial count.
    """
    if not history:
        raise ValueError("sprint history is empty; nothing to simulate from")
    if remaining_points < 0:
        raise ValueError("remaining_points must be >= 0")
    if trials <= 0:
        raise ValueError("trials must be > 0")

    velocities = [s.completed_points for s in history]
    sprint_days = sum(s.length_days for s in history) / len(history)
    rng = random.Random(seed)

    outcomes: list[int | None] = []
    for _ in range(trials):
        if remaining_points == 0:
            outcomes.append(0)
            continue
        done = 0.0
        sprints = 0
        while done < remaining_points and sprints < _MAX_SPRINTS:
            done += rng.choice(velocities)
            sprints += 1
        outcomes.append(sprints if done >= remaining_points else None)

    # None (never finished) sorts to the tail so it lands in the high percentiles.
    ordered = sorted(outcomes, key=lambda value: (value is None, value or 0))

    def as_date(sprints: int | None) -> date | None:
        if sprints is None:
            return None
        return as_of + timedelta(days=math.ceil(sprints * sprint_days))

    p50, p80, p90 = (_percentile(ordered, f) for f in (0.5, 0.8, 0.9))
    return MonteCarloForecast(
        as_of=as_of,
        remaining_points=remaining_points,
        trials=trials,
        seed=seed,
        sprints_p50=p50,
        sprints_p80=p80,
        sprints_p90=p90,
        p50=as_date(p50),
        p80=as_date(p80),
        p90=as_date(p90),
    )
