"""records schema: RAID, cost and the audit log

Second and last of the chained revisions, so head is where the schema is finally
complete. This one creates the per-project RAID and money records (risk, issue,
change_request, budget_line, cost_entry, status_snapshot, stakeholder) plus
change_log, and it chains onto the core revision because change_request points
at baseline and every record hangs off project.

change_log is the table worth pausing on. It lives in ``driftless.db.changelog``,
which ``driftless.models`` deliberately does not re-export — activating its flush
listener is meant to be an explicit call rather than an import side effect. A
migration environment that imports only ``driftless.models`` therefore omits it
silently, autogenerate reports no drift, and the first audited write after
deploy fails on a table that was never created. ``alembic/env.py`` imports both
modules for exactly this reason, and the scaffolding PR carries the test that
keeps it that way.

Autogenerated against a Postgres 16 already migrated to the core revision, so
alembic derived this as a true diff rather than it being split by hand. That run
also reported no drift in the ten core tables, which is independent confirmation
that the first revision matches the models.

Revision ID: 7df21247c4ac
Revises: 8980cbcb2fbb
Create Date: 2026-07-21 17:02:10.285700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "7df21247c4ac"
down_revision: str | None = "8980cbcb2fbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the eight remaining tables, completing the schema at head."""
    op.create_table(
        "change_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("row_id", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.CheckConstraint("operation IN ('insert', 'update', 'delete')", name="ck_operation"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "budget_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("planned_amount", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "category IN ('labour', 'materials', 'services', 'travel', 'contingency')",
            name="ck_category",
        ),
        sa.CheckConstraint("planned_amount >= 0", name="ck_budget_planned_amount"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "category", name="uq_budget_line_project_category"),
    )
    op.create_table(
        "cost_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("incurred_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "category IN ('labour', 'materials', 'services', 'travel', 'contingency')",
            name="ck_category",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_cost_entry_amount"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("impact", sa.Float(), nullable=False),
        sa.Column("response", sa.String(length=20), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "response IN ('avoid', 'mitigate', 'transfer', 'accept')", name="ck_response"
        ),
        sa.CheckConstraint(
            "status IN ('open', 'mitigating', 'closed', 'realised')", name="ck_status"
        ),
        sa.CheckConstraint("impact >= 0", name="ck_risk_impact"),
        sa.CheckConstraint("probability BETWEEN 0 AND 1", name="ck_risk_probability"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stakeholder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("interest", sa.String(length=20), nullable=False),
        sa.Column("influence", sa.String(length=20), nullable=False),
        sa.Column("comms_cadence", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "comms_cadence IN ('weekly', 'fortnightly', 'monthly', 'on_request')",
            name="ck_comms_cadence",
        ),
        sa.CheckConstraint("influence IN ('low', 'medium', 'high')", name="ck_influence"),
        sa.CheckConstraint("interest IN ('low', 'medium', 'high')", name="ck_interest"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("taken_on", sa.Date(), nullable=False),
        sa.Column("percent_complete", sa.Integer(), nullable=False),
        sa.Column("rag_status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=True),
        sa.CheckConstraint("rag_status IN ('green', 'amber', 'red')", name="ck_rag_status"),
        sa.CheckConstraint(
            "percent_complete BETWEEN 0 AND 100", name="ck_snapshot_percent_complete"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "taken_on", name="uq_status_snapshot_project_date"),
    )
    op.create_table(
        "change_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("raised_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resulting_baseline_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "resulting_baseline_id IS NULL OR status = 'approved'", name="ck_change_approved"
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'approved', 'rejected', 'withdrawn')", name="ck_status"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.ForeignKeyConstraint(["resulting_baseline_id"], ["baseline.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "issue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("raised_on", sa.Date(), nullable=False),
        sa.Column("resolved_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("risk_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'resolved', 'closed')", name="ck_status"
        ),
        sa.CheckConstraint(
            "resolved_on IS NULL OR resolved_on >= raised_on", name="ck_issue_dates"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.ForeignKeyConstraint(["risk_id"], ["risk.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Drop the eight tables, children before parents — the exact inverse of upgrade."""
    op.drop_table("issue")
    op.drop_table("change_request")
    op.drop_table("status_snapshot")
    op.drop_table("stakeholder")
    op.drop_table("risk")
    op.drop_table("cost_entry")
    op.drop_table("budget_line")
    op.drop_table("change_log")
