"""core schema: hierarchy and delivery

First of two chained revisions. This one creates the ownership hierarchy
(business, portfolio, program, project, workstream, task) and the per-project
delivery records (baseline, baseline_line, milestone, sprint). The RAID/cost
records and change_log follow in the next revision.

The cut is along the only line that makes the halves independent: nothing here
holds a foreign key into the records tables, so this revision applies and
reverses on its own. The records revision does depend on this one — its
change_request points at baseline, and every record hangs off project.

The schema is therefore complete only at the end of the chain. Do not expect
`alembic check` to be clean after this revision alone; it is checked at head,
in the revision that closes the chain.

Autogenerated against an empty Postgres 16 and then read against the models.
Generating there rather than on SQLite is deliberate: a table that does not yet
exist is rendered from the metadata rather than from reflection, and it is
SQLite reflection that drops named CHECK constraints.

Revision ID: 8980cbcb2fbb
Revises:
Create Date: 2026-07-21 16:56:28.866246

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "8980cbcb2fbb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the ten tables, parents before children so each FK has its target."""
    op.create_table(
        "business",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("delivery_mode", sa.String(length=20), nullable=False),
        sa.Column("status_note", sa.String(length=2000), nullable=True),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "delivery_mode IN ('predictive', 'agile', 'hybrid')", name="ck_delivery_mode"
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio.id"]),
        sa.ForeignKeyConstraint(["program_id"], ["program.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "baseline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('draft', 'approved', 'superseded')", name="ck_status"),
        sa.CheckConstraint("version > 0", name="ck_baseline_version"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_baseline_project_version"),
    )
    op.create_table(
        "milestone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("baseline_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint("status IN ('pending', 'at_risk', 'met', 'missed')", name="ck_status"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sprint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("committed_points", sa.Integer(), nullable=False),
        sa.Column("completed_points", sa.Integer(), nullable=False),
        sa.CheckConstraint("committed_points >= 0", name="ck_committed_points"),
        sa.CheckConstraint("completed_points >= 0", name="ck_completed_points"),
        sa.CheckConstraint("end_date >= start_date", name="ck_sprint_window"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workstream",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("workstream_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("estimate", sa.Float(), nullable=True),
        sa.Column("estimate_unit", sa.String(length=10), nullable=False),
        sa.Column("actual_effort", sa.Float(), nullable=True),
        sa.Column("percent_complete", sa.Integer(), nullable=False),
        sa.CheckConstraint("estimate_unit IN ('points', 'hours')", name="ck_estimate_unit"),
        sa.CheckConstraint(
            "status IN ('todo', 'in_progress', 'blocked', 'done')", name="ck_status"
        ),
        sa.CheckConstraint("percent_complete BETWEEN 0 AND 100", name="ck_percent_complete"),
        sa.ForeignKeyConstraint(["workstream_id"], ["workstream.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "baseline_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("baseline_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("planned_start", sa.Date(), nullable=False),
        sa.Column("planned_finish", sa.Date(), nullable=False),
        sa.Column("planned_cost", sa.Float(), nullable=False),
        sa.CheckConstraint("planned_cost >= 0", name="ck_planned_cost"),
        sa.CheckConstraint("planned_finish >= planned_start", name="ck_planned_window"),
        sa.ForeignKeyConstraint(["baseline_id"], ["baseline.id"]),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "task_id", name="uq_baseline_line_task"),
    )


def downgrade() -> None:
    """Drop the ten tables, children before parents — the exact inverse of upgrade."""
    op.drop_table("baseline_line")
    op.drop_table("task")
    op.drop_table("workstream")
    op.drop_table("sprint")
    op.drop_table("milestone")
    op.drop_table("baseline")
    op.drop_table("project")
    op.drop_table("program")
    op.drop_table("portfolio")
    op.drop_table("business")
