#!/usr/bin/env sh
# Decrypt the SOPS secrets overlay to tmpfs, assemble the runtime configuration,
# migrate the schema, then exec the server. No secret ever touches the image's
# writable layer: it is decrypted into /run/secrets (a tmpfs), sourced into this
# process's environment, and the file is removed before the server starts.
set -eu

SECRETS_ENC=/app/deploy/secrets.enc.env
OVERLAY=/run/secrets/env

if [ ! -f "$SECRETS_ENC" ]; then
    echo "entrypoint: $SECRETS_ENC is missing — create it with sops-edit (see OPERATIONS.md)" >&2
    exit 1
fi

umask 077
sops -d "$SECRETS_ENC" >"$OVERLAY"
# shellcheck disable=SC1090
. "$OVERLAY"
rm -f "$OVERLAY" # values now live only in this process's environment

# Every failure below names the key, the file and the tool, because "absent from
# the decrypted secrets" leaves the operator guessing at both of the last two.
: "${POSTGRES_PASSWORD:?absent — sops-edit deploy/secrets.enc.env and add POSTGRES_PASSWORD}"
# The token may still arrive under its pre-rename name from an existing SOPS
# file; accept either for one deprecation cycle, but require one of them.
DRIFTLESS_API_TOKEN="${DRIFTLESS_API_TOKEN:-${PMHUB_API_TOKEN:-}}"
: "${DRIFTLESS_API_TOKEN:?absent — sops-edit deploy/secrets.enc.env and add DRIFTLESS_API_TOKEN}"
# Hard-required like the two above, deliberately. The session layer fails CLOSED
# without it (driftless/auth/sessions.py), so an instance missing it serves an API
# nobody can sign into through a browser — sign-in, roles, the CSRF-bound forms and
# the page-401 redirect are all dead, and the only symptom is one warning in a log
# nobody reads. Refusing here turns that into a single loud failure at the moment
# the operator is watching `docker compose up`, with the remedy in the message. The
# library stays tolerant (tests and the CLIs run without a secret); a deployment
# that no human can sign into is not a deployment.
: "${DRIFTLESS_SESSION_SECRET:?absent — sops-edit deploy/secrets.enc.env, add DRIFTLESS_SESSION_SECRET}"

# Present is not the same as secret. deploy/secrets.env.example now ships each key with
# no value, so the three checks above already stop a copy nobody edited — but an overlay
# encrypted while the template still carried CHANGE-ME values is a file this repository
# cannot reach, and a published constant satisfies every check above. That instance
# serves happily forever with a session key anyone who has read the repo can forge a
# cookie with. So refuse the value too, here, for the reason the absent case is refused
# here: one failure the operator is looking straight at, remedy included.
# tests/test_deploy_env.py drives this function with every value the template ships, so
# a placeholder spelled some other way fails the suite on the day it is written.
refuse_placeholder() {
    _fix="sops-edit deploy/secrets.enc.env and give $1 a long random value"
    case "$2" in
    *CHANGE-ME*)
        echo "entrypoint: $1 is still the published template placeholder — $_fix" >&2
        exit 1
        ;;
    esac
    # Every value here is machine-generated by the remedy above; a short one was typed
    # by hand, which is the same failure the placeholder was one instance of.
    if [ "${#2}" -lt 24 ]; then
        echo "entrypoint: $1 is shorter than 24 characters — $_fix" >&2
        exit 1
    fi
}

refuse_placeholder POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
refuse_placeholder DRIFTLESS_API_TOKEN "$DRIFTLESS_API_TOKEN"
refuse_placeholder DRIFTLESS_SESSION_SECRET "$DRIFTLESS_SESSION_SECRET"

# Assemble the database URL from parts so no credential literal lives in a file.
DRIFTLESS_DATABASE_URL="postgresql+psycopg://${DRIFTLESS_DB_USER}"
DRIFTLESS_DATABASE_URL="${DRIFTLESS_DATABASE_URL}:${POSTGRES_PASSWORD}@${DRIFTLESS_DB_HOST}:5432/${DRIFTLESS_DB_NAME}"
# Everything in the container reads DRIFTLESS_DATABASE_URL through the one
# resolver, so a single exported value serves the API, Alembic and an
# in-container `driftless report all` / `driftless assess` alike. Sourcing the
# overlay above only makes these SHELL variables: a name missing from this line
# never reaches the server, which is how sign-in once shipped dead.
# tests/test_deploy_env.py derives the list from the package's own env reads.
export DRIFTLESS_DATABASE_URL DRIFTLESS_API_TOKEN DRIFTLESS_SESSION_SECRET

# Build or upgrade the schema before serving.
alembic upgrade head

exec "$@"
