"""PMBOK-6 Integration Management processes (4.1-4.7)."""

from driftless.pmbok.model import KnowledgeArea, Process, ProcessGroup

PROCESSES: tuple[Process, ...] = (
    Process(
        id="4.1",
        name="Develop Project Charter",
        group=ProcessGroup.INITIATING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "business_case",
            "benefits_management_plan",
            "agreements_initial",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_gathering",
            "interpersonal_and_team_skills",
            "meetings",
        ),
        outputs=("project_charter", "assumption_log"),
    ),
    Process(
        id="4.2",
        name="Develop Project Management Plan",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_charter",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_gathering",
            "interpersonal_and_team_skills",
            "meetings",
        ),
        outputs=("project_management_plan",),
    ),
    Process(
        id="4.3",
        name="Direct and Manage Project Work",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_management_plan",
            "change_log",
            "lessons_learned_register",
            "milestone_list",
            "project_communications",
            "approved_change_requests",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "project_management_information_system",
            "meetings",
        ),
        outputs=(
            "deliverables",
            "work_performance_data",
            "issue_log",
            "change_requests",
        ),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="4.4",
        name="Manage Project Knowledge",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_management_plan",
            "lessons_learned_register",
            "project_team_assignments",
            "resource_breakdown_structure",
            "stakeholder_register",
            "deliverables",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "knowledge_management",
            "information_management",
            "interpersonal_and_team_skills",
        ),
        outputs=("lessons_learned_register", "project_management_plan"),
        optional_outputs=("project_management_plan",),
    ),
    Process(
        id="4.5",
        name="Monitor and Control Project Work",
        group=ProcessGroup.MONITORING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_management_plan",
            "assumption_log",
            "issue_log",
            "cost_forecasts",
            "schedule_forecasts",
            "work_performance_information",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_analysis",
            "decision_making",
            "meetings",
        ),
        outputs=("work_performance_reports", "change_requests"),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="4.6",
        name="Perform Integrated Change Control",
        group=ProcessGroup.MONITORING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_management_plan",
            "change_management_plan",
            "configuration_management_plan",
            "scope_baseline",
            "work_performance_reports",
            "change_requests",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "change_control_tools",
            "data_analysis",
            "decision_making",
            "meetings",
        ),
        outputs=("approved_change_requests", "change_log", "project_management_plan"),
        optional_outputs=("approved_change_requests", "project_management_plan"),
    ),
    Process(
        id="4.7",
        name="Close Project or Phase",
        group=ProcessGroup.CLOSING,
        area=KnowledgeArea.INTEGRATION,
        inputs=(
            "project_charter",
            "project_management_plan",
            "accepted_deliverables",
            "business_case",
            "agreements",
            "procurement_documentation",
            "organizational_process_assets",
        ),
        tools_techniques=("expert_judgment", "data_analysis", "meetings"),
        outputs=("final_report", "final_product_service_result", "lessons_learned_register"),
    ),
)
