"""PMBOK-6 Resource Management processes: the six ITTOs of knowledge area 9."""

from driftless.pmbok.model import KnowledgeArea, Process, ProcessGroup

PROCESSES: tuple[Process, ...] = (
    Process(
        id="9.1",
        name="Plan Resource Management",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "project_charter",
            "project_management_plan",
            "scope_baseline",
            "requirements_documentation",
            "risk_register",
            "stakeholder_register",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_representation",
            "organizational_theory",
            "meetings",
        ),
        outputs=("resource_management_plan", "team_charter", "assumption_log"),
    ),
    Process(
        id="9.2",
        name="Estimate Activity Resources",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "resource_management_plan",
            "scope_baseline",
            "activity_list",
            "activity_attributes",
            "assumption_log",
            "cost_estimates",
            "resource_calendars",
            "risk_register",
        ),
        tools_techniques=(
            "expert_judgment",
            "bottom_up_estimating",
            "analogous_estimating",
            "parametric_estimating",
            "data_analysis",
            "project_management_information_system",
        ),
        outputs=("resource_requirements", "basis_of_estimates", "resource_breakdown_structure"),
    ),
    Process(
        id="9.3",
        name="Acquire Resources",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "resource_management_plan",
            "project_schedule",
            "resource_requirements",
            "resource_calendars",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "decision_making",
            "interpersonal_and_team_skills",
            "pre_assignment",
            "negotiation",
            "virtual_teams",
        ),
        outputs=(
            "physical_resource_assignments",
            "project_team_assignments",
            "resource_calendars",
            "change_requests",
        ),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="9.4",
        name="Develop Team",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "resource_management_plan",
            "lessons_learned_register",
            "project_schedule",
            "project_team_assignments",
            "resource_calendars",
            "team_charter",
        ),
        tools_techniques=(
            "colocation",
            "virtual_teams",
            "interpersonal_and_team_skills",
            "team_building",
            "recognition_and_rewards",
            "training",
            "individual_and_team_assessments",
        ),
        outputs=("team_performance_assessments", "change_requests"),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="9.5",
        name="Manage Team",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "resource_management_plan",
            "issue_log",
            "lessons_learned_register",
            "project_team_assignments",
            "team_charter",
            "work_performance_reports",
            "team_performance_assessments",
        ),
        tools_techniques=(
            "interpersonal_and_team_skills",
            "conflict_management",
            "influencing",
            "project_management_information_system",
        ),
        outputs=("change_requests", "issue_log", "project_team_assignments"),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="9.6",
        name="Control Resources",
        group=ProcessGroup.MONITORING,
        area=KnowledgeArea.RESOURCE,
        inputs=(
            "resource_management_plan",
            "issue_log",
            "physical_resource_assignments",
            "project_schedule",
            "resource_breakdown_structure",
            "resource_requirements",
            "work_performance_data",
            "agreements",
        ),
        tools_techniques=(
            "data_analysis",
            "problem_solving",
            "interpersonal_and_team_skills",
            "influencing",
            "project_management_information_system",
        ),
        outputs=("work_performance_information", "change_requests"),
        optional_outputs=("change_requests",),
    ),
)
