"""PMBOK Risk Management processes (7): Plan through Monitor Risks."""

from driftless.pmbok.model import KnowledgeArea, Process, ProcessGroup

PROCESSES: tuple[Process, ...] = (
    Process(
        id="11.1",
        name="Plan Risk Management",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RISK,
        inputs=(
            "project_charter",
            "project_management_plan",
            "stakeholder_register",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=("expert_judgment", "data_analysis", "stakeholder_analysis", "meetings"),
        outputs=("risk_management_plan",),
    ),
    Process(
        id="11.2",
        name="Identify Risks",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "scope_baseline",
            "schedule_baseline",
            "cost_baseline",
            "assumption_log",
            "stakeholder_register",
            "enterprise_environmental_factors",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_gathering",
            "data_analysis",
            "interpersonal_and_team_skills",
            "prompt_lists",
            "meetings",
        ),
        outputs=("risk_register", "risk_report", "assumption_log"),
        optional_outputs=("risk_report",),
    ),
    Process(
        id="11.3",
        name="Perform Qualitative Risk Analysis",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "scope_baseline",
            "assumption_log",
            "risk_register",
            "stakeholder_register",
            "enterprise_environmental_factors",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_gathering",
            "risk_probability_and_impact_assessment",
            "risk_categorization",
            "data_representation",
            "meetings",
        ),
        outputs=("risk_register", "risk_report", "assumption_log"),
        optional_outputs=("risk_report",),
    ),
    Process(
        id="11.4",
        name="Perform Quantitative Risk Analysis",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "scope_baseline",
            "schedule_baseline",
            "cost_baseline",
            "risk_register",
            "cost_estimates",
        ),
        tools_techniques=(
            "expert_judgment",
            "representations_of_uncertainty",
            "simulation",
            "sensitivity_analysis",
            "decision_tree_analysis",
            "influence_diagrams",
        ),
        outputs=("risk_report",),
    ),
    Process(
        id="11.5",
        name="Plan Risk Responses",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "risk_register",
            "risk_report",
            "cost_baseline",
            "resource_management_plan",
            "lessons_learned_register",
        ),
        tools_techniques=(
            "expert_judgment",
            "data_gathering",
            "interpersonal_and_team_skills",
            "strategies_for_threats",
            "strategies_for_opportunities",
            "contingent_response_strategies",
            "strategies_for_overall_project_risk",
            "decision_making",
        ),
        outputs=("change_requests", "risk_register", "risk_report"),
        optional_outputs=("change_requests", "risk_report"),
    ),
    Process(
        id="11.6",
        name="Implement Risk Responses",
        group=ProcessGroup.EXECUTING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "risk_register",
            "risk_report",
            "lessons_learned_register",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "interpersonal_and_team_skills",
            "project_management_information_system",
        ),
        outputs=("change_requests", "risk_register", "risk_report"),
        optional_outputs=("change_requests", "risk_report"),
    ),
    Process(
        id="11.7",
        name="Monitor Risks",
        group=ProcessGroup.MONITORING,
        area=KnowledgeArea.RISK,
        inputs=(
            "risk_management_plan",
            "risk_register",
            "risk_report",
            "issue_log",
            "lessons_learned_register",
            "work_performance_data",
            "work_performance_reports",
        ),
        tools_techniques=("data_analysis", "audits", "meetings"),
        outputs=(
            "work_performance_information",
            "change_requests",
            "risk_register",
            "risk_report",
        ),
        optional_outputs=("change_requests", "risk_report"),
    ),
)
