"""PMBOK-6 Schedule Management processes: the six ITTOs of knowledge area 6."""

from driftless.pmbok.model import KnowledgeArea, Process, ProcessGroup

PROCESSES: tuple[Process, ...] = (
    Process(
        id="6.1",
        name="Plan Schedule Management",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "project_charter",
            "project_management_plan",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=("expert_judgment", "data_analysis", "meetings"),
        outputs=("schedule_management_plan",),
    ),
    Process(
        id="6.2",
        name="Define Activities",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "schedule_management_plan",
            "scope_baseline",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "expert_judgment",
            "decomposition",
            "rolling_wave_planning",
            "meetings",
        ),
        outputs=("activity_list", "activity_attributes", "milestone_list", "change_requests"),
        optional_outputs=("change_requests",),
    ),
    Process(
        id="6.3",
        name="Sequence Activities",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "schedule_management_plan",
            "activity_list",
            "activity_attributes",
            "milestone_list",
            "project_scope_statement",
            "enterprise_environmental_factors",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "precedence_diagramming_method",
            "dependency_determination",
            "leads_and_lags",
            "project_management_information_system",
        ),
        outputs=("project_schedule_network_diagram", "activity_attributes"),
    ),
    Process(
        id="6.4",
        name="Estimate Activity Durations",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "schedule_management_plan",
            "activity_list",
            "activity_attributes",
            "milestone_list",
            "risk_register",
            "resource_requirements",
            "resource_calendars",
            "enterprise_environmental_factors",
        ),
        tools_techniques=(
            "expert_judgment",
            "analogous_estimating",
            "parametric_estimating",
            "three_point_estimating",
            "bottom_up_estimating",
            "data_analysis",
        ),
        outputs=("duration_estimates", "basis_of_estimates"),
    ),
    Process(
        id="6.5",
        name="Develop Schedule",
        group=ProcessGroup.PLANNING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "schedule_management_plan",
            "activity_list",
            "activity_attributes",
            "project_schedule_network_diagram",
            "duration_estimates",
            "resource_calendars",
            "risk_register",
        ),
        tools_techniques=(
            "schedule_network_analysis",
            "critical_path_method",
            "resource_optimization",
            "schedule_compression",
            "leads_and_lags",
            "agile_release_planning",
        ),
        outputs=("schedule_baseline", "project_schedule", "schedule_data", "project_calendars"),
        optional_outputs=("schedule_data", "project_calendars"),
    ),
    Process(
        id="6.6",
        name="Control Schedule",
        group=ProcessGroup.MONITORING,
        area=KnowledgeArea.SCHEDULE,
        inputs=(
            "project_management_plan",
            "project_schedule",
            "work_performance_data",
            "project_calendars",
            "schedule_data",
            "organizational_process_assets",
        ),
        tools_techniques=(
            "data_analysis",
            "critical_path_method",
            "project_management_information_system",
        ),
        outputs=(
            "work_performance_information",
            "schedule_forecasts",
            "change_requests",
            "schedule_baseline",
        ),
        optional_outputs=("change_requests",),
    ),
)
